[package]
name = "bpe_tokenizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.32", features = ["derive"] }
nom = "7.1.1"
nom-unicode = "0.3.0"
rayon = "1.6.1"
serde_json = "1.0.91"
